services:
  - type: web
    name: rag-playground-backend
    env: python
    plan: standard # Use standard plan for more memory
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: MAX_MEMORY_MB
        value: 1024
    autoDeploy: false
